/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1f880bec-56da-4aaf-8920-7ea599eba5eb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_mzA1SonwR",
    "aws_user_pools_web_client_id": "2k4676qov74l0oovdtcfvpfff0",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://rvagj4fpavas5iwsuclufjgege.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
<<<<<<< HEAD
    "aws_appsync_apiKey": "da2-ztmqs2daxfarnbwdr3f2alnsj4"
=======
    "aws_appsync_apiKey": "da2-ztmqs2daxfarnbwdr3f2alnsj4",
    "aws_user_files_s3_bucket": "pmacbetafiles135904-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
>>>>>>> 9346c4296420f80a7de36a5863d6d1f94c71db5a
};


export default awsmobile;
